### PR TITLE
[ ] replaced with get()

### PR DESCRIPTION
**Pull request by annstriganova**
Changes according to https://apps.axibase.com/redmine/issues/4949#note-18

### CODE REVIEW

**Comment by rodionos** [comment]
We can still use `[index]`. It's a syntax that is more concise and I would keep this syntax option.

**Comment by annstriganova** [comment]
Rev. 18871. Find out several specifics. There are attempts to access objects:

**collection(string s) [string]**
- `[index]` ---> `java.lang.ClassCastException: java.util.LinkedHashSet cannot be cast to java.lang.Class`  _Issue 5090_
- `get(index)` ---> `[Error: unable to resolve method using strict-mode: java.util.Collection.get(java.lang.Integer)] [Near : {... v2=v1.get(1); ....}] ^ [Line: 2, Column: 7] 
Form contains errors`

**getEntities(string m, string s, string e, string p) [object]**
- `[index]` ---> no errors, but  it's impossible to access entity object fields
- `get(index)` ---> ok

**split(string s, string p) [string]**
- `[index]` ---> ok
- `get(index)` ---> ok

**list(string s[, string p]) [string]**
- `[index]` ---> ok
- `get(index)` ---> ok

**rule_windows(string r, string p) [object]**
- `[index]` ---> no errors, but  it's impossible to access window object fields
- `get(index)` ---> no errors, but  it's impossible to access window object fields
_Issue 4925_

**property_values([string e, ]string s[, string d]) [string]**
- `[index]` ---> `java.lang.ClassCastException: java.util.LinkedHashSet cannot be cast to java.lang.Class`
- `get(index)` ---> `[Error: unable to resolve method using strict-mode: java.util.Set.get(java.lang.Integer)] [Near : {... v3=v1.get(0); ....}] ^ [Line: 3, Column: 7] 
Form contains errors`

**Comment by raipc** [comment]
`java.lang.ClassCastException` occurs because of a bug in MVEL. The actual reason is that Set interface doesn't support taking element by index. I created a [pull request](https://github.com/mvel/mvel/pull/147) with fix.

**Comment by annstriganova** [comment]
Docs for `rule_windows(string r, string p) [object]` will be updated in separate PR.

**Pull request merged**
