### PR TITLE
element-lint

### PR DESCRIPTION
**Pull request by kghamilton89**

### CODE REVIEW

**Comment by rodionos** [comment]
I had to disable some rules as they're broken. Review the remaining 100 or so issues raised by linter. Some of the which involve `may` for example are false alerts. may usage is legit, so we would need to decide what to do with `may` rule.

**Comment by kghamilton89** [comment]
I added some white space to the the blacklist in `/docs-util` to combat false positives which seems to have worked:

* We were getting instances of Hadoop flagged as Had.
* Determinate as Terminate.
* Click One as Click On.
* Curly as Curl.

We're still failing here because of words like Let's as in Let's Encrypt but I think you can see for yourself that all true errors have been rectified.

**Comment by kghamilton89** [comment]
One more change to `/docs-util` based on false positive, Lowered being flagged as Were past tense. White space added. I think that means we're about ready to merge.

**Comment by kghamilton89** [comment]
I found there were some double spaces that occurred from removing unneeded words as well.

**Pull request merged**
