### PR TITLE
scheduled-rules-refactor

### PR DESCRIPTION
**Pull request by kghamilton89**
# 5486

Refactor of `scheduled-rules.md`:
* Writing style and content
* Screenshots reflect current UI

### CODE REVIEW

**Comment by kghamilton89** [comment]
* Build is failing but because or Travis errors, not rule violations.

**Comment by rodionos** [comment]
Please review my changes. Also, add more examples on conditions that control when the rule is triggered, e.g. 9am each day, only once; day before non-working day; 6 am and 18 am on Tuesday. Add a discussion on how last_open function can be used to prevent the rule from firing too often.

**Comment by kghamilton89** [comment]
* Changes reviewed.
* New examples added.
* This build will fail because I've linked to the yet un-merged Holiday Calendars Documentation PR.

**Comment by rodionos** [comment]
@kghamilton89 - pls retest

**Comment by kghamilton89** [comment]
Build is failing because there are links from #695 which haven't been merged.

**Pull request merged**
