### PR TITLE
update-toc

### PR DESCRIPTION
**Pull request by kghamilton89**
Issue #5643: Update **Administration** page Table of Contents to be more similar to others.

### CODE REVIEW

**Comment by kghamilton89** [comment]
@rodionos I don't understand the changes you'd like to see.

**Comment by rodionos** [comment]
image

Group links in TOC md according to how they grouped in ATSD docs menu.

**Comment by kghamilton89** [comment]
Conveniently enough, all of the links were included somewhere in the left-side menu. The only section which was not was the entire `/migration` sub-directory. I added it to the left-side menu as well as the `README.md` page.

**Comment by rodionos** [comment]
Are there pages in /administration that are not part of TOC (not accessible from TOC)?

**Comment by kghamilton89** [comment]
@rodionos Not with the addition of the `/migration` sub-directory. When I created the first version of the TOC, I simply when down the list in VSCode and added each file to what I thought was the appropriate section. When I refactored it, I moved the existing entries to their new locations and was left with no remainder.

**Pull request merged**
